config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :exercices, only: [:index, :show]

  resources :categories, only: [:index, :show] do
    resources :exercices, only: [:index, :show]
  end

  resources :subscriptions

  # Cette route est pour les utilisateurs qui veulent voir ou gérer leurs abonnements
  get 'my_subscriptions', to: 'subscriptions#user_subscriptions', as: 'user_subscriptions'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :subscriptions
  belongs_to :exercice
  has_many :users, through: :subscriptions
  # Autres méthodes et associations...
end

app/models/exercice.rb
class Exercice < ApplicationRecord
  has_many :categories
  has_many :users, through: :categories
  has_one_attached :photo

  validates :name, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :subscriptions
  has_many :categories, through: :subscriptions

  validates :first_name, presence: true
  validates :last_name, presence: true

  before_validation :set_default_role

  enum role: [:user, :un_particulier, :un_club_sportif, :admin]

  private

  def set_default_role
    self.role ||= :user
  end

  # def subscribed_to?(category)
  #   self.categories.include?(category)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:index], if: :exercices_controller?

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role, :first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:role, :first_name, :last_name])
  end

  def pundit_user
    current_user
  end

  private

  def exercices_controller?
    controller_name == "exercices"
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/exercices_controller.rb
class ExercicesController < ApplicationController
  before_action :set_exercice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  def index
    @exercices = policy_scope(Exercice)
    authorize @exercices
  end

  def show
    @exercice = Exercice.find(params[:id])
  end

  def new
    @exercice = Exercice.new
    authorize @exercice
  end

  def create
    @exercice = Exercice.new(exercice_params)
    authorize @exercice
    if @exercice.save
      flash[:notice] = "Le nouvel exercice a été créé"
      redirect_to exercice_path(@exercice)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @exercice.update(exercice_params)
    flash[:notice] = "L'exercice a été modifié"
    redirect_to exercice_path(@exercice)
  end

  def destroy
    @exercice.destroy
    flash[:notice] = "L'exercice a été supprimé"
    redirect_to exercices_path, status: :see_other
  end

  private

  def set_exercice
    @exercice = Exercice.find(params[:id])
    authorize @exercice
  end

  def exercice_params
    params.require(:exercice).permit(:name, :description, :difficulty_level, :duration, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/subscriptions_controller.rb
# app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :ensure_admin

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Catégorie créée avec succès.'
    else
      render :new
    end
  end

  # Ajoutez les méthodes edit, update, destroy, etc.

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def ensure_admin
    # Mettez en place une logique pour vous assurer que l'utilisateur est un administrateur
    redirect_to root_path, alert: 'Accès non autorisé!' unless current_user&.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exercices/_form.html.erb
      <%= simple_form_for(@exercice) do |f| %>
        <!-- Your form inputs here -->
  <%= f.input :name, label: false, placeholder: "Nom" %>
  <%= f.input :description, label: false, placeholder: "Description" %>
  <%= f.input :difficulty_level, label: false, placeholder: "Niveau de difficulté de l'exercice" %>
  <%= f.input :duration, label: false, placeholder: "Durée de l'exercice" %>
  <%# <%= f.input :video_url, label: false, placeholder: "URL de la vidéo" %>
  <%= f.input :photo, as: :file %>
  <%# <%= f.association :categories,
                    as: :check_boxes,
                    input_html: { class: "tag-selector" },
                    item_wrapper_class: 'tag-item' %>
        <%= f.button :submit, class: "btn-primary", value: "Enregistrer les modifications" %>
        <%= link_to 'Retour aux exercices', exercices_path, class: "btn-secondary" %>
      <% end %>

app/views/exercices/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
<h1>Voici le titre de l'exercice à modifier : <%= @exercice.name %></h1>
 <%= render "form", exercice: @exercice %>
    </div>
    <div class="col-6">
      <div class="image-container">
        <%= image_tag("banner2.jpg", alt: "Image de l'exercice") %>
      </div>
    </div>
  </div>
</div>

app/views/exercices/index.html.erb
<div class="container">
  <div class="row">
    <h1>Découvre des exercices adaptés à ton envie de Botobo !</h1>
    <ul class="cards-exercices">
      <% @exercices.each do |exercice| %>
        <li>
          <%= link_to exercice_path(exercice) do %>
            <div class="exercice-image">
              <% if exercice.photo.attached? %>
                <%= cl_image_tag exercice.photo.key, height: 300, width: 400, crop: :fill %>
              <% else %>
                <%= image_tag "default_exercice_image.jpg", size: "300x200", alt: "Image par défaut" %>
              <% end %>
            </div>
            <div class="exercice-info">
              <i class="fa-solid fa-fire-alt"></i> <%= exercice.duration %> minutes
              <span class="exercice-name"><%= exercice.name %></span>
              <span class="exercice-description"><%= exercice.description %></span>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
<% if policy(Exercice.new).create? %>
  <%= link_to "Créer un nouvel exercice", new_exercice_path, class: "btn btn-secondary" %>
<% end %>

  </div>
</div>

app/views/exercices/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
    <%= if policy(Exercice).create?%>
      <h1>Ajoute un exercice !</h1>
      <%= simple_form_for(@exercice) do |f| %>
  <%= f.input :name, label: false, placeholder: "Nom" %>
  <%= f.input :description, label: false, placeholder: "Description" %>
  <%= f.input :difficulty_level, label: false, placeholder: "Niveau de difficulté de l'exercice" %>
  <%= f.input :duration, label: false, placeholder: "Durée de l'exercice" %>
   <%= f.input :photo, as: :file %>
   <%# <div>
    <h1>Télécharge ton fichier</h1>
    <div>
      <button id="upload_widget" class="cloudinary-button">Upload files</button>
    </div> %>
  <%# </div> %>
  <%# <%= f.input :video_url, label: false, placeholder: "URL de la vidéo" %>
  <%# <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%# <%= f.input :videos, as: :file, input_html: { multiple: true } %>
  <%# <%= f.association :categories,
                    as: :check_boxes,
                    input_html: { class: "tag-selector" },
                    item_wrapper_class: 'tag-item' %>
        <%= f.button :submit, class: "btn-primary", value: "Enregistrer" %>
      <% end %>
        <%= link_to 'Retour aux exercices', exercices_path, class: "btn-secondary" %>
      <% end %>
    </div>
    <div class="col-6">
      <div class="image-container">
        <%= image_tag("banner2.jpg", alt: "Image de l'exercice") %>
      </div>
    </div>
  </div>
</div>

app/views/exercices/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col">
      <h3><%= @exercice.name %></h3>
      <div class="text-center">
        <div class="row justify-content-evenly">
          <div class="col-md-4">
            <p><%= icon('fa-regular', 'bell') %> <%= @exercice.duration %> minutes</p>
            <p><i class="fa-solid fa-fire-alt"></i> <%= @exercice.description %></p>
            <% if @exercice.photo.attached? %>
              <%= cl_image_tag @exercice.photo.key, height: 300, width: 400, crop: :fill %>
            <% else %>
              <%= image_tag "default_exercice_image.jpg", alt: "Default Image", class: "img-fluid" %>
            <% end %>
          </div>
          <div class="col-md-4">
            <a href="/exercices/new" class="btn btn-secondary">Créer un exercice</a>
          <% if policy(@exercice).edit? %>
          <%= link_to "Modifier cet exercice", edit_exercice_path(@exercice), class: "btn btn-primary" %>
          <% end %>

           <% if policy(@exercice).destroy? %>
          <%= link_to "Supprimer cet exercice",
            exercice_path(@exercice),
            data: {turbo_method: :delete, turbo_confirm: "Etes vous sur?"}
          %>
          <% end %>
          </div>
        </div>
      </div>
      <%= link_to "Retour vers les exercices", exercices_path, class: "btn btn-secondary mt-3" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Botobo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
        <%= render "shared/flashes" %>

        <script src="https://upload-widget.cloudinary.com/global/all.js" type="text/javascript">
        </script>


    <%= yield %>

  </body>
  <%= render "shared/footer" %>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url('<%= image_path('banner.png') %>');">
  <div class="container">
    <h1>Bo to Bo* !!</h1>
    <h2>Shake your health !</h2>
    <p>* Bouge ton boule</p>
    <div class="banner-text" style="margin-top: 30px" >
     <% if user_signed_in? %>
        <div class="banner-buttons">
          <%= link_to "Découvre les exercices", exercices_path, class: "btn btn-primary"%>
            <%= link_to "Crée un exercice", new_exercice_path, class: "btn btn-secondary" if current_user.role == 'un club sportif'%>

      <% else %>
        <div class="banner-buttons">
         <%= link_to "Découvre les exercices", exercices_path, class: "btn btn-primary"%>
          <%= link_to "Abonne toi !", new_subscription_path, class: "btn btn-primary" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container" style="text-align: center"><h3>3 bonnes raisons de commencer à Bo to Bo :</h3></div>

<div class="container">
  <div class="row card-container">
    <!-- Card 1 -->
    <div class="col-md-4">
      <div class="card-product">
        <!-- Pond de couleur -->
        <div class="color-circles">
          <div class="color-circle" style="background: #2a9d8fff;"></div>
          <div class="color-circle" style="background: #e9c46aff;"></div>
          <div class="color-circle" style="background: #f4a261ff;"></div>
          <div class="color-circle" style="background: #e76f51ff;"></div>
        </div>
        <%= image_tag("homme.png") %>
        <div class="card-product-infos">
          <!-- Titre et description -->
          <h2>Booster votre forme</h2>
          <p>Votre description ici...</p>
        </div>
      </div>
    </div>

    <!-- Card 2 -->
    <div class="col-md-4">
      <div class="card-product">
        <!-- Pond de couleur -->
        <div class="color-circles">
          <div class="color-circle" style="background: #2a9d8fff;"></div>
          <div class="color-circle" style="background: #e9c46aff;"></div>
          <div class="color-circle" style="background: #f4a261ff;"></div>
          <div class="color-circle" style="background: #e76f51ff;"></div>
        </div>
        <div class="color-point"></div>
        <%= image_tag("mental.jpg") %>
        <div class="card-product-infos">
          <!-- Titre et description -->
          <h2>Sharper votre mental</h2>
          <p>Votre description ici...</p>
        </div>
      </div>
    </div>

    <!-- Card 3 -->
    <div class="col-md-4">
      <div class="card-product">
        <!-- Pond de couleur -->
        <div class="color-circles">
          <div class="color-circle" style="background: #2a9d8fff;"></div>
          <div class="color-circle" style="background: #e9c46aff;"></div>
          <div class="color-circle" style="background: #f4a261ff;"></div>
          <div class="color-circle" style="background: #e76f51ff;"></div>
        </div>
        <div class="color-point"></div>
        <%= image_tag("health.jpg") %>
        <div class="card-product-infos">
          <!-- Titre et description -->
          <h2>Rester en santé</h2>
          <p>Votre description ici...</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <div class="footer">
      <div class="footer-links">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
       </div>
    <div class="footer-copyright">
        This footer is made with <i class="fas fa-heart"></i> at Komunity
     </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "A propos de nous", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mon profil", "#", class: "dropdown-item" %>
              <%= link_to "Mon activité", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/subscriptions/new.html.erb
<%= simple_form_for @subscription, url: subscriptions_path do |f| %>
  <%= f.input :category_ids, as: :check_boxes, collection: Category.all.map { |c| [c.name, c.id] }, label: "Catégories" %>
  <%= f.button :submit, 'Souscrire' %>
<% end %>

app/views/users/profile.html.erb
<%= simple_form_for @subscription do |f| %>
  <% Category.all.each do |category| %>
    <%= f.input :category_ids, as: :check_boxes, collection: [[category.name, category.id]], label: false, inline_label: category.name %>
  <% end %>

  <%= f.button :submit, 'Souscrire' %>
<% end %>